### ISSUE TITLE
SROS2 demo using Keymint now not working with Fast RTPS

### ISSUE THREAD

**Issue by ruffsl** [ruffsl/ros2_docker_demos#2]
As of dafae39ff0427ed4433eeaa7fad5931ae86d5b2b , it seems that what works find for `rmw_connext_cpp` is not working for `rmw_fastrtps_cpp`. When attempting to use the keystore generated by the keymint script, `rmw_connext_cpp` will generate the following error:

```
[SECURITY Error] Error validating the local participant identity. () -> Function init
[RTPS_PARTICIPANT Error] Cannot create participant due to security initialization error -> Function createParticipant
[PARTICIPANT Error] Problem creating RTPSParticipant -> Function createParticipant
terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
  what():  failed to initialize rcl node: create_node() could not create participant, at /tmp/binarydeb/ros-bouncy-rmw-fastrtps-cpp-0.5.1/src/rmw_node.cpp:91, at /tmp/binarydeb/ros-bouncy-rcl-0.5.0/src/rcl/node.c:336
```

To reproduce, simply follow along with the [README.md](https://github.com/ruffsl/ros2_docker_demos/blob/dafae39ff0427ed4433eeaa7fad5931ae86d5b2b/sros2/README.md), but take note to enable the approrate environment verables in the [docker-compose.yml](https://github.com/ruffsl/ros2_docker_demos/blob/dafae39ff0427ed4433eeaa7fad5931ae86d5b2b/sros2/docker-compose.yml) to enable security and the appropriate `RMW_IMPLEMENTATION`. You can comment out `network_mode: "host"` to avoid broadcasting in your local networks.

Depending on which script you use, `keystore_setup.bash` will do fine, yet `keymint_setup.bash` will lead to the error above, presumably due to the tighter permission it compiles as opposed to `keystore_setup.bash` use of wildcards.

ping @mikaelarguedas

**Comment by ruffsl** [comment]
Ok, think I found three issues when comparing to `keystore_setup` script.
1. the default governance config was old and missing the newly added `enable_liveliness_protection` element. Connext didn't seem to mind it missing, but fastrtps lucky does.
2. Small issue with how kemint's keymake was signing the xml files, as fastrtps seem to require that `Content-Type: text/plain\n\n` prefix the xml string when embedded in the singed `.ps7` file.
3. Some issue with how keymint generates the CA cert. Connext is fine with it, but fastrtps only takes the the openssl generate cert style.

**Comment by mikaelarguedas** [comment]
1.
Yeah FastRTPS implement the xml checking more strictly (for the better!) it also lead to https://github.com/ros2/sros2/pull/44, though a bit too strictly for some tags (https://github.com/eProsima/Fast-RTPS/issues/245).
3.
I'm not sure what the spec expects in that matter. I remember having issues because before and it was fixed once https://github.com/eProsima/Fast-RTPS/commit/1e84b97b21c96fa01c50656f2348532434480985 added expectation for the comma separated version (matching the examples from the spec).

**Comment by ruffsl** [comment]
Ok, I solved the 3rd issue as well. Turns out fastrtps also checks to make sure the singing CA has the correct x509 extensions configured for a CA, [e.g.](https://github.com/ros/ros_comm/blob/f95b4a5de2acb4fb53f0e9a4cff47dcef928eac5/tools/sros/conf/keyserver_config.yaml):

``` yaml
x509_extensions: # https://access.redhat.com/documentation/en-US/Red_Hat_Certificate_System/8.0/html/Admin_Guide/Standard_X.509_v3_Certificate_Extensions.html
    BasicConstraints: # This extension is used during the certificate chain verification process to identify CA certificates and to apply certificate chain path length constraints
      critical: True # PKIX Part 1 requires that this extension be marked critical. This extension is evaluated regardless of its criticality
      value:
        ca: True
        path_length: 1 # max length of CA chain tat could extend from current cert
```

Perhaps connext should also be doing this :thinking: ! 

Although it doesn't seem fastrtps requires it to be critical to be set to True, which really messes with my head given TLS requires this; additionally, why bother erroring out due to the `BasicConstraints` extension being absent if you not going to require it also be marked as **critical=True**?

I guess this enlarges the certificate payloads over the wire with one more x509 extension, but perhaps it warranted. I just don't see this requirement stated in the speck, or it could be implicit from `9.3 Builtin Authentication: DDS:Auth:PKI-DH`, in bold:

> An X.509 Certificate **that chains up to** the Shared Identity CA, that binds the Public Key of the DomainParticipant to the Distinguished Name (subject name) for the DomainParticipant.
 
Perhaps we could ping some connext and fastrtps folks?
